# Generated by Django 6.1 on 2026-08-10 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('prontuario', models.AutoField(primary_key=True, serialize=False, verbose_name='Prontuário')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Paciente')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('especialidade', models.CharField(choices=[('cirurgia_oncologica', 'Cirurgia Oncológica'), ('cirurgia_toracica', 'Cirurgia Torácica'), ('oncoginecologia', 'Oncoginecologia'), ('cabeca_pescoco', 'Cirurgia de Cabeça e Pescoço'), ('mastologia', 'Mastologia'), ('neurocirurgia', 'Neurocirurgia'), ('urologia', 'Urologia'), ('oncohematologia', 'Oncohematologia'), ('oncologia_clinica', 'Oncologia Clínica')], max_length=50, verbose_name='Especialidade')),
                ('data_entrada', models.DateField(blank=True, null=True, verbose_name='Data de Entrada')),
                ('diagnostico', models.CharField(blank=True, choices=[('C50', 'C50 - Neoplasia maligna da mama'), ('C61', 'C61 - Neoplasia maligna da próstata'), ('C34', 'C34 - Neoplasia maligna dos brônquios e dos pulmões'), ('OUTROS', 'Outros')], max_length=10, null=True, verbose_name='Diagnóstico (CID-10)')),
                ('data_diagnostico', models.DateField(blank=True, null=True, verbose_name='Data do Diagnóstico')),
                ('fez_cirurgia', models.BooleanField(default=False, verbose_name='Cirurgia?')),
                ('data_cirurgia', models.DateField(blank=True, null=True)),
                ('fez_qt', models.BooleanField(default=False, verbose_name='Quimioterapia (QT)?')),
                ('data_qt', models.DateField(blank=True, null=True)),
                ('fez_rt', models.BooleanField(default=False, verbose_name='Radioterapia (RT)?')),
                ('data_rt', models.DateField(blank=True, null=True)),
                ('fez_cirurgia_rt', models.BooleanField(default=False, verbose_name='Cirurgia + RT?')),
                ('data_cirurgia_rt', models.DateField(blank=True, null=True)),
                ('fez_cirurgia_qt', models.BooleanField(default=False, verbose_name='Cirurgia + QT?')),
                ('data_cirurgia_qt', models.DateField(blank=True, null=True)),
                ('fez_qt_cirurgia', models.BooleanField(default=False, verbose_name='QT + Cirurgia?')),
                ('data_qt_cirurgia', models.DateField(blank=True, null=True)),
                ('fez_rt_cirurgia', models.BooleanField(default=False, verbose_name='RT + Cirurgia?')),
                ('data_rt_cirurgia', models.DateField(blank=True, null=True)),
                ('fez_qt_rt', models.BooleanField(default=False, verbose_name='QT + RT?')),
                ('data_qt_rt', models.DateField(blank=True, null=True)),
                ('fez_rt_qt', models.BooleanField(default=False, verbose_name='RT + QT?')),
                ('data_rt_qt', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
