# Generated by Django 6.1 on 2026-08-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento_oncologico_hrc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
