# Generated by Django 6.1 on 2026-08-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento_oncologico_hrc', '0002_paciente_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='data_entrada',
            field=models.DateField(verbose_name='Data de Entrada'),
        ),
    ]
