# Generated by Django 6.1 on 2026-08-10 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento_oncologico_hrc', '0004_alter_paciente_data_entrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='data_entrada',
            field=models.DateField(default='2026-01-01', verbose_name='Data de Entrada'),
            preserve_default=False,
        ),
    ]
