# Generated by Django 6.1 on 2026-08-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento_oncologico_hrc', '0005_alter_paciente_data_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='data_imunoterapia',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Imunoterapia'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='data_indicacao_cirurgia',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Indicação'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='imunoterapia',
            field=models.BooleanField(default=False, verbose_name='Imunoterapia'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='indicacao_cirurgia',
            field=models.BooleanField(default=False, verbose_name='Indicação de Cirurgia'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='qual_cirurgia',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Qual Cirurgia?'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fez_cirurgia',
            field=models.BooleanField(default=False, verbose_name='Cirurgia'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fez_cirurgia_qt',
            field=models.BooleanField(default=False, verbose_name='Cirurgia + QT'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fez_cirurgia_rt',
            field=models.BooleanField(default=False, verbose_name='Cirurgia + RT'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fez_qt',
            field=models.BooleanField(default=False, verbose_name='Quimioterapia (QT)'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fez_qt_cirurgia',
            field=models.BooleanField(default=False, verbose_name='QT + Cirurgia'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fez_qt_rt',
            field=models.BooleanField(default=False, verbose_name='QT + RT'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fez_rt',
            field=models.BooleanField(default=False, verbose_name='Radioterapia (RT)'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fez_rt_cirurgia',
            field=models.BooleanField(default=False, verbose_name='RT + Cirurgia'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fez_rt_qt',
            field=models.BooleanField(default=False, verbose_name='RT + QT'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='prontuario',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Prontuário'),
        ),
    ]
