# Generated by Django 6.1 on 2026-08-11 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento_oncologico_hrc', '0006_paciente_data_imunoterapia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='data_cirurgia',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='data_cirurgia_qt',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='data_cirurgia_rt',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='data_imunoterapia',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='data_indicacao_cirurgia',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='data_qt',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='data_qt_cirurgia',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='data_qt_rt',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='data_rt',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='data_rt_cirurgia',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='data_rt_qt',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='fez_cirurgia',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='fez_cirurgia_qt',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='fez_cirurgia_rt',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='fez_qt',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='fez_qt_cirurgia',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='fez_qt_rt',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='fez_rt',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='fez_rt_cirurgia',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='fez_rt_qt',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='imunoterapia',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='indicacao_cirurgia',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='qual_cirurgia',
        ),
        migrations.CreateModel(
            name='HistoricoTratamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_tratamento', models.CharField(max_length=100, verbose_name='Tipo')),
                ('data', models.DateField(verbose_name='Data do Tratamento')),
                ('detalhes', models.CharField(blank=True, max_length=200, null=True, verbose_name='Detalhes')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamentos', to='monitoramento_oncologico_hrc.paciente')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
